name: Run Tests and Upload Allure Report

on:
  workflow_dispatch:

jobs:
  test-and-upload:
    runs-on: ubuntu-latest

    env:
      ALLURE_RESULTS_DIR: build/allure-results
      ALLURE_SERVER_URL: http://91.211.249.37:30355
      PROJECT_ID: work-task-autotests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permissions to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run tests with Gradle
        run: ./gradlew clean test

      - name: List Allure results directory
        if: always()
        run: ls -l ${ALLURE_RESULTS_DIR}

      - name: Upload Allure results using allurectl
        if: always()
        run: |
          curl -L -o allurectl https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64
          chmod +x allurectl
          ./allurectl upload ${ALLURE_RESULTS_DIR} \
            --endpoint ${ALLURE_SERVER_URL} \
            --project-name ${PROJECT_ID}


      - name: Show Allure report URL
        if: always()
        run: |
          echo "Allure report available at: ${ALLURE_SERVER_URL}/projects/${PROJECT_ID}/reports/latest/index.html"
